---
title: "Deep and Statistical Learning WS 21-22"
output: 
  github_document:
    default
  pdf_document:
    default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_format = "all") })

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      eval = FALSE)
```

# Analysis of Berlins Airbnb Data using statistical and deep learning methods. 

> Am besten dieser File in HTML angucken (wenn nicht in GitHub). To edit --> Rstudio.  

## TO DO

## Orga
- Define "our" deadlines 
- a concrete scope of the project (to avoid working in vain).  


### Data preprocesing (Sebi/Tobi)
 

#### Listings : Turn to metric
- seasson (summer/winter variable). 
- Tobi runs Werkstudent script to create custum seasson variable. 


#### Bild (Tobi)

- Liste mit detected objekten erstellen und auf r-projekt
- Bild detection and segmentation auf colab
  - https://colab.research.google.com/drive/1OCOeZJkA1_2hFLSbFUkez5vrRzIu2UpA?usp=sharing

##### Farbe/helligkeit

- Möglichkeit mit pillow package in python
- Kelvin si colour
- Lumen unit

##### Bildqualität mit cnn

- Email bilder scraping mit matse klären
- drei Gruppen haben es definitiv geschafft alle Bilder zu scrapen. 


##### Picture Scene analsis
- das gleiche skript nutzt matse. 
- muss lokal aufgebaut werden dann sollte es laut matse klappen

### Text i.e reviews /NLP
- Word stemming von isi projekt (tobi arbeit)  auf rviews anwenden
- Vielleicht intervalle bilden
- Seb macht zuerst noch weiter und deligiert dann

### Analisis/Model Construction 

#### Regression (Sebi)
- Run regression without latitutude, longitude 
- run regression without highly correlated variables. 

## Get a grap for boosting. 
- Last project? how to include in a model?
- Mixed Data Multiimput CNN: Nicht gut erklärbar. 
- GBT2
- adaboost usage with airbnb data. 
- metric for comparison with covnets. 



#### Regularization/ (Sebi/Tobi)
- 6. Scale up and develope a model that overfits.
    + ?
- 7. Regularize a model and tune hyperparemeters
    + ?

### Report (15 Seiten) (Sebi/Tobi)

#### Write (Sebi/Tobi)



#### Literature (Sebi/Tobi)

- Für picture detection websiten direkt auf citavi
- Citavi grupieren und sortieren
-	Reference website und save als pdf oder über local file also pdfs runterladen
- Alle angeschauten modelle zu detection und segmentation auf citavi in die gliederung die seb eröffnet
- "Wissen" fenster auf citavi für cnn weitermachen

 

### Best practices
- Für Tobi: Branching in GIT
- Citavi: Add references and inmediatly document the corresponding PDF




## Anmeldedaten für DeepL Videos bei Manning (DeepLearnng with R in motion):
-   tobirinnert@gmail.com
-   DeepLearningWS2021

## Data
siehe .Rmd in Data folder. 









    
