---
title: "Dnn_to_ber_results"
author: "Tobias_R"
date: "21 Februar 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Dependencies 
```{r}
library(MLmetrics)
library(keras)
library(here)
library(ggplot2)
```

```{r}
load(file = here("model", "final train performance", "final_results.Rda"))
```

```{r}
load(here("data","munich", "m_metric_pic_abs_temp.Rda"))
```

```{r}
full_mun <- metric_pic_abs_temp
mun_targets <- log(full_mun["price"])
mun_targets <- unlist(c(mun_targets))
mun_data <- subset(x = full_mun, select = -c(price))
mun_data <- array(mun_data)

mean <- colMeans(mun_data) # mean of each column
std <- apply(mun_data, 2, sd) # stdev of each column
mun_data <- scale(mun_data, center = mean, scale = std)
```

```{r}
model <- load_model_tf(here("model", "dnn", "nn_abs_full_wide"))
```

```{r}
predictions_mun <- model %>% predict(x = mun_data)
```

```{r}
rmse_dnn_mun <- RMSE(predictions_mun, mun_targets)
R2_dnn_mun <- R2_Score(predictions_mun, mun_targets)
MAE_dnn_mun <- MAE(predictions_mun, mun_targets)
```

```{r}
res_dnn <- list(rmse_dnn_mun, R2_dnn_mun, MAE_dnn_mun)
performance$DNN <- res_dnn
```

```{r}
test_df <- t(performance)
test_df <- apply(test_df, 2, FUN = unlist)
test_df <- as.data.frame.array(test_df)
test_df <- as.data.frame.array(test_df)
```

