---
title: "add_image_df"
author: "Tobias_R"
date: "1 Februar 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dependencies
```{r}
library(readr)
library(reticulate)
```


Load image_df in:

```{r}
pd <- import("pandas")
det_bright_mean_df <- pd$read_pickle("det_bright_mean_df")
#pic_id == id
```


```{r}
dataset_mod <- read_csv("1_mvars.csv")
```

```{r}
det_bright_mean_df <- subset(x = det_bright_mean_df, select = -c(pic_paths,detect_obj))
```


## transform logical values to binary is easier to do it here
```{r}
dataset_mod[(length(dataset_mod)-4):length(dataset_mod)] <- lapply(X = dataset_mod[(length(dataset_mod)-4):length(dataset_mod)], FUN = as.numeric)
#View(dataset_mod[(length(dataset_mod)-4):length(dataset_mod)])
```

```{r}
dataset_mod <- subset(x = dataset_mod, select = -c(host_id))
```


```{r}
View(det_bright_mean_df)
```

## should we drop minimum_minimum_nights, maximum_minimum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm as they seem to hold the same infos as other columns?

```{r}
View(dataset_mod)
```


```{r}
image_an_mvars_df <- merge(dataset_mod, det_bright_mean_df, by.x = "id", by.y = "pic_id")
```

```{r}
View(image_an_mvars_df[0:10,])
```

```{r}
save(image_an_mvars_df ,file="image_an_mvars_df.Rda")
```

```{r}
sum(is.na(image_an_mvars_df))
```



